# Generated by Django 3.0.4 on 2020-05-08 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NurtureHealthApp', '0002_auto_20200507_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=250)),
                ('treatment_originalprice', models.FloatField()),
                ('treatment_actualprice', models.FloatField()),
                ('treatment_image', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('details', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('treatment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NurtureHealthApp.Department')),
            ],
        ),
    ]
