# Generated by Django 3.0.4 on 2020-05-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurtureHealthApp', '0003_add_treatment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_treatment',
            options={'verbose_name_plural': 'Add Treatment'},
        ),
        migrations.AlterField(
            model_name='add_treatment',
            name='treatment_actualprice',
            field=models.CharField(max_length=250),
        ),
    ]
