# Generated by Django 3.0.4 on 2020-05-29 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NurtureHealthApp', '0004_auto_20200511_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='address_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='address_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='clinic_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='clinic_info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='postal_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
