# Generated by Django 3.0.4 on 2020-05-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NurtureHealthApp', '0006_auto_20200530_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_treatment',
            options={'verbose_name_plural': 'Add Treatment'},
        ),
    ]
