# Generated by Django 3.0.4 on 2020-05-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NurtureHealthApp', '0008_appoint_rev'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appoint',
            options={'verbose_name_plural': 'Appoints'},
        ),
        migrations.AlterModelOptions(
            name='rev',
            options={'verbose_name_plural': 'Revs'},
        ),
    ]
