# Generated by Django 3.0.4 on 2020-05-30 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NurtureHealthApp', '0010_auto_20200530_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NurtureHealthApp.Department'),
        ),
    ]
