# Generated by Django 3.0.4 on 2020-05-31 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NurtureHealthApp', '0011_register_table_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_table',
            name='specialization',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='NurtureHealthApp.Department'),
            preserve_default=False,
        ),
    ]
