# Generated by Django 3.0.4 on 2020-05-31 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NurtureHealthApp', '0012_auto_20200531_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NurtureHealthApp.Department'),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='specialization',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='NurtureHealthApp.Department'),
        ),
    ]
